### ISSUE TITLE
Installing on Sublime Text 4 erroring

### ISSUE THREAD

**Issue by anlek** [fnando/sublime-codefmt#1]
When trying to install your awesome looking plugin on Sublime Text build 4113 (latest) I get the following error in the console:

```python
reloading python 3.3 plugin Codefmt.utils
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/andrew/Library/Application Support/Sublime Text 3/Installed Packages/Codefmt.sublime-package/utils.py", line 4, in <module>
ImportError: No module named 'pathlib'
Unable to parse binding {command: format_code_file, keys: []}
Unknown key not sure
Unable to parse binding {command: yaml_path, keys: [not sure]}
```

**Comment by fnando** [comment]
Looks like `pathlib` is available starting on 3.4+.

https://docs.python.org/3.9/library/pathlib.html#module-pathlib

**Comment by anlek** [comment]
Interesting!

So when I run the following in my sublime console:
```python
import sys
print(sys.version)
```

I get: `3.8.8 (default, Mar 10 2021, 13:52:20)`

Surprised I uninstalled `codefmt` again and saw this in output in the console:

```
unloading python 3.3 plugin Codefmt.FormatCodeFile
```

Seems like maybe my Sublime is using a odd version of python for plugins.

I'll research and report if I figure out how to switch it.

**Comment by anlek** [comment]
So based on the [Release Notes](https://www.sublimetext.com/blog/articles/sublime-text-4) from May 21, 2021. It states:
> **Updated Python API**
The Sublime Text API has been updated to Python 3.8, while keeping backwards compatibility with packages built for Sublime Text 3. The API has been significantly expanded, adding features that allow plugins like LSP to work better than ever. Read the revamped documentation here.

Lower down the file it follows it up with:
>PYTHON 3.8 API
> * Added a Python 3.8 API environment for plugins
> * Plugins can choose Python version via `.python-version` file in plugin folder
> * Existing plugins are fully supported via legacy Python 3.3 API
> * Many API improvements and additions - see API section for more details

This might be why I'm having the issue.

@fnando are you not seeing the same issue in your sublime? Or are you not installing it via the **Package Manager**?

**Comment by anlek** [comment]
I've submitted a [PR](https://github.com/fnando/sublime-codefmt/pull/2) that should fix this issue in Sublime Text 4.

I do believe that it will still be an issue in Sublime Text 3, however, I no longer have that editor to test.

**Comment by fnando** [comment]
Thanks for the info. That's probably the case here. 

I just pushed a [new commit](https://github.com/fnando/sublime-codefmt/commit/5783a48f2e697e74b54013856def9b4ddbddbd4b) adding `.python-version` as `3.8`. I also added the python version to the debug output, so you can easily check what sublime is using.

Let me know how it goes!

**Comment by anlek** [comment]
Worked (at least it installed without errors).

**Comment by anlek** [comment]
Now when I run it I get this:
```python
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1518, in run_
    return self.run(edit)
  File "/Users/andrew/Library/Application Support/Sublime Text 3/Installed Packages/Codefmt.sublime-package/FormatCodeFile.py", line 7, in run
  File "/Users/andrew/Library/Application Support/Sublime Text 3/Installed Packages/Codefmt.sublime-package/utils.py", line 37, in format_code_file
  File "/Users/andrew/Library/Application Support/Sublime Text 3/Installed Packages/Codefmt.sublime-package/utils.py", line 122, in find_matching_formatters
TypeError: 'NoneType' object is not iterable
```

**Comment by fnando** [comment]
Are you running in debug mode? Is there any info there?

**Comment by anlek** [comment]
I created a new ticket for that issue here: https://github.com/fnando/sublime-codefmt/issues/3 (with more info).

**Comment by anlek** [comment]
I'm closing this issue as it has been fixed.
